feat: FE-632 - bol name change
myparcelnl/js-sdk pull request #141
Opened 2023-10-19 08:51 UTC by Vincentvanleeuwen

## Ticket 
[FE-604](https://myparcelnl.atlassian.net/browse/FE-604) - Als MyParcel wil ik de naam van Bol.com wijzigen in bol

## Description

Changed bol.com to bol.

2023-10-19 09:24 UTC, Cysword requested changes

2023-10-25 07:45 UTC, Cysword approved these changes

2023-10-25 08:28 UTC, EdieLemoine requested changes
titel klopt niet, en name is nog `bol.com`

2023-10-25 10:06 UTC, EdieLemoine approved these changes

2023-10-25 10:08 UTC, merged